
project_id = "tvwofhbebafpdbqxrngb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
port = 54325

[functions]
port = 54326

[functions.scrape-prayer-times]
verify_jwt = false
